{{- if .Values.gateway.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: litellm-gateway-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: litellm-gateway-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
  - {{ .Values.host }}
---
{{- if .Values.grafana.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-gateway-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: grafana-gateway-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
  - {{ .Values.gateway.grafanaHost }}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-gateway-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: prometheus-gateway-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
  - {{ .Values.gateway.prometheusHost }}
{{- end }}