{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
    {{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRefKey }}
        decodingStrategy: None
    {{- end }}
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.clusterSecretStore }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: litellm-external-secret
{{- end }}
