{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gateway.gatewayClassName }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
{{- end }}
---
{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    cert-manager.io/issuer-kind: Issuer
    cert-manager.io/issuer-group: cert-manager.io
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
  - name: https-litellm
    hostname: {{ .Values.host }}
    protocol: HTTPS
    port: 443
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: litellm-tls
  - name: https-grafana
    hostname: {{ .Values.gateway.grafanaHost }}
    protocol: HTTPS
    port: 443
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: grafana-tls
  - name: https-prometheus
    hostname: {{ .Values.gateway.prometheusHost }}
    protocol: HTTPS
    port: 443
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: prometheus-tls
{{- end }}
---
{{- if and .Values.gateway.enabled .Values.grafana.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
    namespace: {{ .Values.gateway.namespace }}
    sectionName: https-grafana
  hostnames:
  - {{ .Values.gateway.grafanaHost }}
  rules:
  - backendRefs:
    - name: {{ .Release.Name }}-grafana
      port: 80
{{- end }}
---
{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
    namespace: {{ .Values.gateway.namespace }}
    sectionName: https-prometheus
  hostnames:
  - {{ .Values.gateway.prometheusHost }}
  rules:
  - backendRefs:
    - name: {{ .Release.Name }}-prometheus-server
      port: 80
{{- end }}
---
{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: litellm
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
    namespace: {{ .Values.gateway.namespace }}
    sectionName: https-litellm
  hostnames:
  - {{ .Values.host }}
  rules:
  - backendRefs:
    - name: litellm
      port: 4000
{{- end }}