apiVersion: k0rdent.mirantis.com/v1beta1
kind: Management
metadata:
  name: kcm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      k0rdent.mirantis.com/component: kcm
spec:
  release: {{ .Values.kcmRelease }}
  providers:
    - name: cluster-api-provider-k0sproject-k0smotron
    - name: projectsveltos
      config: 
        addonController:
          controller:
            additionalVolumes:
              - name: helm-cache
                emptyDir: {}
            additionalVolumeMounts:
              - name: helm-cache
                mountPath: /home/nonroot/.cache
