apiVersion: v2
name: kcm-wrapper
description: A helm chart to manage KCM releases
type: application
version: 1.0.0
appVersion: "1.2.0"
dependencies:
  - name: kcm
    version: "1.2.0"
    repository: "oci://ghcr.io/k0rdent/kcm/charts"
