kcm:
  namespaceOverride: "kcm-system"
  fullnameOverride: "kcm"
  nameOverride: "kcm"

  controller:
    createManagement: false

  admissionWebhook:
    enabled: true

  cert-manager:
    enabled: true
    crds:
      enabled: true
      keep: false

  cluster-api-operator:
    enabled: true

kcmRelease: "kcm-1-2-0"
