apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: {{ include "awsmachinetemplate.worker.name" . }}
  annotations:
    {{- include "aws-standalone.keepPolicy" . | nindent 4 }}
spec:
  template:
    spec:
      {{- if not (quote .Values.worker.amiID | empty) }}
      ami:
        id: {{ .Values.worker.amiID }}
      {{- end }}
      imageLookupFormat: {{ .Values.worker.imageLookup.format }}
      imageLookupOrg: "{{ .Values.worker.imageLookup.org }}"
      imageLookupBaseOS: {{ .Values.worker.imageLookup.baseOS }}
      instanceType: {{ .Values.worker.instanceType }}
      # Instance Profile created by `clusterawsadm bootstrap iam create-cloudformation-stack`
      iamInstanceProfile: {{ .Values.worker.iamInstanceProfile }}
      cloudInit:
        # Makes CAPA use k0s bootstrap cloud-init directly and not via SSM
        # Simplifies the VPC setup as we do not need custom SSM endpoints etc.
        insecureSkipSecretsManager: true
      publicIP: {{ .Values.publicIP }}
      rootVolume:
        size: {{ .Values.worker.rootVolumeSize }}
        encrypted: true
      {{- with .Values.worker.nonRootVolumes }}
      nonRootVolumes: {{- toYaml . | nindent 8 }}
      {{- end }}
      uncompressedUserData: {{ .Values.worker.uncompressedUserData }}
      # --- START CUSTOMIZATION: Do not remove ---
      instanceMetadataOptions:
        httpTokens: {{ .Values.worker.instanceMetadataOptions.httpTokens }}
        httpPutResponseHopLimit: {{ .Values.worker.instanceMetadataOptions.httpPutResponseHopLimit }}
      # --- END CUSTOMIZATION ---
